import { Jost } from 'next/font/google';
import "./globals.css";
import NavigationBar from "@/components/global/NavigationBar";

const jost = Jost({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <NavigationBar />
        {children}
        </body>
    </html>
  );
}
